#!/bin/bash

# This is a simple File Explore script. It allows you
# to interactively traverse the directory tree of your
# system, and then select files to either read, write,
# or execute

# We are going to do a little black magic later
shopt -s expand_aliases
alias List="ls -ilh"
alias fzf="fzf -m --reverse"

# Display for the types of permissions
file_activity(){
    echo Read
    echo Write
    echo Details
    echo Copy
    echo View Image
    echo View PDF
    echo Watch Video
    echo Execute
    echo Delete
}

file_info(){
    echo File Type
    echo Permissions
    echo Ownership
    echo Size
    echo Date Created
    echo Inode
}

# If the user has a different editor set in their ENV then
# this selector will use that instead of vim
edit_select(){
    if [ -z $EDITOR ]
    then
        [ -$1 $2 ] && vim $2 || echo "No $3 Permissions"
    else
        [ -$1 $2 ] && ls $2 | xargs -r -o $EDITOR ||\
        echo "No $3 Permissions"     
    fi
}

# Allow user to choose if they see hidden files or not
[[ $1 == "-a" ]] && vis_flag="-a" || vis_flag=""

# Ask the user where to start
echo -n "Root of the tree: "
read -r base

# fzf does not play nice with ~
if [ $base == "~" ]
then
    base_dir=$HOME
elif [[ $base = ~* ]]
then
    base_dir=$HOME/${base#~*}
else
    base_dir=${base}
fi

# Black Magic
if [ ! -d ${base_dir} ]
then
    alias goto="cat > /dev/null <<"
    new_dir=${base_dir}
else
    alias goto="#"
fi
goto "#GOTO"
# END Black Magic

new_dir="${base_dir}/$(ls ${vis_flag} ${base_dir} | fzf)"

# As long as directories are being selected continue in the env
while [ -d ${new_dir} ]
do
    next_dir=$(ls ${vis_flag} ${new_dir} | fzf)
    # Need a way to gracefully exit the script
    [ -z ${next_dir} ] && echo "No Directory choosen" && exit 1
    new_dir=${new_dir}/${next_dir}
done

# Black Magic Call
#GOTO

# User desides what they want to do with the file
result=$(file_activity | fzf)

case $result in
"Read")
        # Can user read the file? If so, it will open.
        edit_select "r" ${new_dir} "read"
        ;;
"Write")
        # Can user write the file? If so, it will open.
        edit_select "w" ${new_dir} "write"
        ;;
"Details")
        # Display different bits of information about the file selected
        detail=$(file_info | fzf)
        case $detail in
        "File Type")
                file ${new_dir} | awk '{print $2}' | fzf
                ;;
        "Permissions")
                List ${new_dir} | awk '{print $2}' | fzf
                ;;
        "Ownership")
                List ${new_dir} | awk '{print $4 " " $5}' | fzf
                ;;
        "Size")
                List ${new_dir} | awk '{print $6}' | fzf
                ;;
        "Date Created")
                List ${new_dir} | awk '{print $7 " " $8 " " $9}' | fzf
                ;;
        "Inode")
                List ${new_dir} | awk '{print $1}' | fzf
                ;;
        *)
                exit 1
        esac    
        ;;
"Copy")
        echo 'Which directory will files be copied too?'
        echo 'Location MUST be an absolute path'
        read -r loc
        files=$(echo ${new_dir} | sed 's/^..//g' | awk -F \/ '{print $NF}')
        dir=$(echo ${new_dir} | awk -F \/ 'sub(FS $NF,x)')
        for i in $files:
        do
            sel_file=$(echo "${dir}/$i" | awk -F \: '{print $1}')
            echo $sel_file
            cp $sel_file $loc
        done
        ;; 
"View Image")
        # What kind of picture you trying to look at
        [ -r ${new_dir} ] && sxiv ${new_dir} || echo "Unable to open Picture"
        ;;
"View PDF")
        # Look at you exercising your brain
        [ -r ${new_dir} ] && epdfview ${new_dir} || echo "Unable to open PDF"
        ;;
"Watch Video")
        # Ok pics are one thing but this is a Christian Server Sir
        list=$(ls ${new_dir} | awk '/list/ {print "videos.list"}' )
        if [ ${list} == "videos.list" ]
        then
            vid=$(awk '{print}' ${new_dir} | fzf)
            [ -r ${new_dir} ] && mpv ${vid} || echo "Unable to play Video"
        else
            [ -r ${new_dir} ] && mpv ${new_dir} || echo "Unable to play Video"
        fi
        ;;
"Execute")
        # If user can exec the file the script will inform them and
        # give them the relevant path to the file. Otherwise it will
        # simply inform them they can not exec.
        [ -x ${new_dir} ] && echo "You have permission" && echo ${new_dir} ||\
         echo "You do not have permission"
        ;;
"Delete")
        # Sometimes you just want to start over fresh.
        rm -i ${new_dir}
        ;;
*)
        # Quit playing around
        echo "No proper value given"
        exit 1
esac

# Remove the junk from the screen
clear
